services:
  - type: web
    name: avva-home-foods
    env: docker
    dockerfilePath: ./Dockerfile
    port: 8080
    plan: free
    memoryMB: 512
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: SERVER_SERVLET_CONTEXT_PATH
        value: /
    region: oregon
    autoDeployFromGitHub: true
    maxShutdownDelaySeconds: 30
